build/
transform
node_modules/
resources/scripts/*.map
resources/lib/
resources/css/leaflet/
resources/css/prismjs
resources/images/openseadragon
resources/images/leaflet
resources/i18n/common
test/cypress/screenshots/
test/cypress/videos/
test/cypress/downloads/
.DS_Store