// StandardJS, should-style assertions
// GUI tests for Authentication UI functionality
// Generated by jinks - DO NOT EDIT manually

describe('TEI-Publisher Authentication UI', () => {
  beforeEach(() => {
    // Universal intercepts (loginStub, timelineStub) are automatically set up in support/e2e.js
    // Note: loginStub is used in this test to verify unauthenticated access

    // Set desktop viewport to ensure all elements are visible
    cy.viewport(1280, 720)

    cy.visit('/browse.html')
    
    // Wait for page to stabilize
    cy.get('body').should('be.visible')
  })

  describe('Login UI Elements', () => {
    it('displays login prompt with form fields', () => {
      // Click login button to open dialog
      cy.get('#login')
        .should('be.visible')
        .click()
      
      // Wait for login dialog to open and verify form elements
      cy.get('pb-dialog[open], dialog[open]', { timeout: 5000 }).should('be.visible')
      cy.contains('Login').should('be.visible')
      cy.contains('User').should('be.visible')
      cy.contains('Password').should('be.visible')
      cy.get('input[name="user"]').should('be.visible')
      cy.get('input[name="password"]').should('be.visible')
      cy.get('button').contains('Login').should('be.visible')
    })

    it('shows login link', () => {
      // Login link should be visible in the UI
      cy.get('#login').should('be.visible')
    })

    it('displays login form correctly', () => {
      // Click login button to open dialog
      cy.get('#login').should('be.visible').click()
      
      // Wait for dialog and verify form structure
      cy.get('pb-dialog[open], dialog[open]', { timeout: 5000 }).should('be.visible')
      cy.get('input[name="user"]').should('be.visible')
      cy.get('input[name="password"]').should('be.visible')
      cy.get('button').contains('Login').should('be.visible')
    })

    it('shows login form fields clearly', () => {
      // Click login button to open dialog
      cy.get('#login').should('be.visible').click()
      
      // Wait for dialog and check that form fields are visible and labeled
      cy.get('pb-dialog[open], dialog[open]', { timeout: 5000 }).should('be.visible')
      cy.contains('User').should('be.visible')
      cy.contains('Password').should('be.visible')
      cy.get('input[name="user"]').should('be.visible')
      cy.get('input[name="password"]').should('be.visible')
    })
  })

  describe('Restricted Content UI', () => {
    it('shows restricted content structure', () => {
      // Check that pb-restricted elements exist (they may not be visible without login)
      cy.get('pb-restricted').should('exist')
      
      // Check that restricted content has proper structure
      cy.get('pb-restricted').then(($elements) => {
        if ($elements.length > 0) {
          // pb-restricted elements should exist but may not be visible without authentication
          cy.get('pb-restricted').should('not.have.attr', 'show')
        }
      })
    })

    it('displays fallback content when not authenticated', () => {
      // Check for fallback content in restricted sections
      cy.get('pb-restricted').then(($elements) => {
        if ($elements.length > 0) {
          // Should show fallback content or be hidden
          cy.get('pb-restricted').should('not.have.attr', 'show')
        }
      })
    })

    it('has proper restricted content styling', () => {
      // Check that restricted content has appropriate CSS classes
      cy.get('pb-restricted').then(($elements) => {
        if ($elements.length > 0) {
          // Should have proper styling for restricted state
          cy.get('pb-restricted').should('exist')
        }
      })
    })
  })

  describe('Authentication UI Responsiveness', () => {
    it('adapts login UI to mobile viewport', () => {
      cy.viewport(375, 667) // iPhone SE
      
      // On mobile, login is in the mobile menu - open it first
      cy.get('button[data-toggle=".mobile.menubar"]').should('be.visible').click()
      
      // Wait for mobile menu to open and find login link in shadow DOM
      cy.get('.mobile.menubar:not(.hidden)', { timeout: 5000 }).should('be.visible')
      cy.get('.mobile.menubar:not(.hidden) pb-login#login, .mobile.menubar:not(.hidden) #login', { timeout: 5000 })
        .should('exist')
        .shadow()
        .find('a', { includeShadowDom: false })
        .should('be.visible')
        .click()
      
      // Wait for login dialog to open and verify it's visible on mobile
      cy.get('pb-dialog[open], dialog[open]', { timeout: 5000 }).first().should('be.visible')
      cy.get('pb-dialog[open], dialog[open]').first().within(() => {
        cy.contains('Login').should('be.visible')
      })
      cy.get('input[name="user"]').should('be.visible')
      cy.get('input[name="password"]').should('be.visible')
    })

    it('adapts login UI to tablet viewport', () => {
      cy.viewport(768, 1024) // iPad
      
      // On tablet, login may be in the mobile menu - open it first
      cy.get('button[data-toggle=".mobile.menubar"]').should('be.visible').click()
      
      // Wait for mobile menu to open and find login link in shadow DOM
      cy.get('.mobile.menubar:not(.hidden)', { timeout: 5000 }).should('be.visible')
      cy.get('.mobile.menubar:not(.hidden) pb-login#login, .mobile.menubar:not(.hidden) #login', { timeout: 5000 })
        .should('exist')
        .shadow()
        .find('a', { includeShadowDom: false })
        .should('be.visible')
        .click()
      
      // Wait for login dialog to open and verify it's visible on tablet
      cy.get('pb-dialog[open], dialog[open]', { timeout: 5000 }).should('be.visible')
      // On tablet, dialog content might be clipped, so check for elements directly
      cy.contains('Login', { timeout: 5000 }).should('exist')
      cy.get('input[name="user"]', { timeout: 5000 }).should('exist')
      cy.get('input[name="password"]', { timeout: 5000 }).should('exist')
    })
  })

  describe('Authentication UI Accessibility', () => {
    it('has accessible login form', () => {
      // Click login button to open dialog
      cy.get('#login').should('be.visible').click()
      
      // Wait for dialog and check that form is accessible
      cy.get('pb-dialog[open], dialog[open]', { timeout: 5000 }).should('be.visible')
      cy.contains('Login').should('be.visible')
      cy.get('input[name="user"]').should('be.visible')
      cy.get('input[name="password"]').should('be.visible')
      
      // Check for proper form labels
      cy.contains('User').should('be.visible')
      cy.contains('Password').should('be.visible')
    })

    it('provides clear form labels and structure', () => {
      // Click login button to open dialog
      cy.get('#login').should('be.visible').click()
      
      // Wait for dialog and check that form has clear labels
      cy.get('pb-dialog[open], dialog[open]', { timeout: 5000 }).should('be.visible')
      cy.contains('User').should('be.visible')
      cy.contains('Password').should('be.visible')
      
      // Verify form inputs are properly labeled
      cy.get('input[name="user"]').should('be.visible')
      cy.get('input[name="password"]').should('be.visible')
      cy.get('button').contains('Login').should('be.visible')
    })
  })
})

