build
transform
node_modules
resources/scripts/*.js
resources/scripts/*.map
resources/lib/
resources/css/leaflet/
resources/css/prismjs
resources/images/openseadragon
resources/images/leaflet
resources/i18n/common