// StandardJS, should-style assertions
// API tests for info/version functionality
// Generated by jinks - DO NOT EDIT manually

describe('/api/version', () => {
  it('queries version information', () => {
    cy.api('/api/version')
      .its('status').should('eq', 200)

    cy.api('/api/version').then(({ body }) => {
      cy.wrap(body).should('have.property', 'api')
      cy.wrap(body).should('have.property', 'app')
      cy.wrap(body.app && body.app.name).should('be.a', 'string')
    })
  })
})

